/*
 * This file is generated by jOOQ.
 */
package telsos.db.maas;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import telsos.db.maas.tables.Profiles;

/**
 * A class modelling indexes of tables in jee.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index PROFILES_EMAIL_IDX = Internal.createIndex(
      DSL.name("profiles_email_idx"), Profiles.PROFILES,
      new OrderField[] { Profiles.PROFILES.EMAIL }, true);
}
