/*
 * This file is generated by jOOQ.
 */
package telsos.db.maas;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import telsos.db.maas.tables.Profiles;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jee extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>jee</code>
   */
  public static final Jee JEE = new Jee();

  /**
   * The table <code>jee.profiles</code>.
   */
  public final Profiles PROFILES = Profiles.PROFILES;

  /**
   * No further instances allowed
   */
  private Jee() {
    super("jee", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Sequence<?>> getSequences() {
    return Arrays.<Sequence<?>>asList(Sequences.PROFILES_ID_SEQ);
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.<Table<?>>asList(Profiles.PROFILES);
  }
}
