/*
 * This file is generated by jOOQ.
 */
package telsos.db.maas;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/**
 * Convenience access to all sequences in jee.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

  /**
   * The sequence <code>jee.profiles_id_seq</code>
   */
  public static final Sequence<Long> PROFILES_ID_SEQ = Internal.createSequence(
      "profiles_id_seq", Jee.JEE, SQLDataType.BIGINT.nullable(false), null,
      null, null, null, false, null);
}
