/*
 * This file is generated by jOOQ.
 */
package telsos.db.maas;

import telsos.db.maas.tables.Profiles;

/**
 * Convenience access to all tables in jee.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>jee.profiles</code>.
   */
  public static final Profiles PROFILES = Profiles.PROFILES;
}
