/*
 * This file is generated by jOOQ.
 */
package telsos.db.maas.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import telsos.db.maas.tables.Profiles;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilesRecord extends UpdatableRecordImpl<ProfilesRecord>
    implements Record5<Long, String, String, Long, String> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>jee.profiles.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>jee.profiles.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>jee.profiles.email</code>.
   */
  public void setEmail(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>jee.profiles.email</code>.
   */
  public String getEmail() {
    return (String) get(1);
  }

  /**
   * Setter for <code>jee.profiles.first_name</code>.
   */
  public void setFirstName(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>jee.profiles.first_name</code>.
   */
  public String getFirstName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>jee.profiles.amount</code>.
   */
  public void setAmount(Long value) {
    set(3, value);
  }

  /**
   * Getter for <code>jee.profiles.amount</code>.
   */
  public Long getAmount() {
    return (Long) get(3);
  }

  /**
   * Setter for <code>jee.profiles.passwd</code>.
   */
  public void setPasswd(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>jee.profiles.passwd</code>.
   */
  public String getPasswd() {
    return (String) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row5<Long, String, String, Long, String> fieldsRow() {
    return (Row5) super.fieldsRow();
  }

  @Override
  public Row5<Long, String, String, Long, String> valuesRow() {
    return (Row5) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return Profiles.PROFILES.ID;
  }

  @Override
  public Field<String> field2() {
    return Profiles.PROFILES.EMAIL;
  }

  @Override
  public Field<String> field3() {
    return Profiles.PROFILES.FIRST_NAME;
  }

  @Override
  public Field<Long> field4() {
    return Profiles.PROFILES.AMOUNT;
  }

  @Override
  public Field<String> field5() {
    return Profiles.PROFILES.PASSWD;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getEmail();
  }

  @Override
  public String component3() {
    return getFirstName();
  }

  @Override
  public Long component4() {
    return getAmount();
  }

  @Override
  public String component5() {
    return getPasswd();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getEmail();
  }

  @Override
  public String value3() {
    return getFirstName();
  }

  @Override
  public Long value4() {
    return getAmount();
  }

  @Override
  public String value5() {
    return getPasswd();
  }

  @Override
  public ProfilesRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public ProfilesRecord value2(String value) {
    setEmail(value);
    return this;
  }

  @Override
  public ProfilesRecord value3(String value) {
    setFirstName(value);
    return this;
  }

  @Override
  public ProfilesRecord value4(Long value) {
    setAmount(value);
    return this;
  }

  @Override
  public ProfilesRecord value5(String value) {
    setPasswd(value);
    return this;
  }

  @Override
  public ProfilesRecord values(Long value1, String value2, String value3,
      Long value4, String value5) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached ProfilesRecord
   */
  public ProfilesRecord() {
    super(Profiles.PROFILES);
  }

  /**
   * Create a detached, initialised ProfilesRecord
   */
  public ProfilesRecord(Long id, String email, String firstName, Long amount,
      String passwd) {
    super(Profiles.PROFILES);

    setId(id);
    setEmail(email);
    setFirstName(firstName);
    setAmount(amount);
    setPasswd(passwd);
  }
}
